// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeminjamanRuangan.Data;

#nullable disable

namespace PeminjamanRuangan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PeminjamanRuangan.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Keperluan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomorRuangan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TanggalKembali")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TanggalPinjam")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Peminjamans");
                });
#pragma warning restore 612, 618
        }
    }
}
